language: python
python:
  - 2.7
env:
  - BUILD_TYPE="Debug"
  - BUILD_TYPE="Release"
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  # Print NumPy version that is already installed by Travis CI:
  - python -c "import numpy; print numpy.__version__"
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - git submodule init
  - git submodule update clawutil visclaw riemann classic
  - python setup.py install
  - cd ..
before_script:
  # Print CPU info for debugging purposes:
  - cat /proc/cpuinfo
  - gfortran -v
  - /usr/bin/f95 -v
install:
  - make
script:
  - cd tests/acoustics3d
  - make .output
notifications:
  email: false