language: python
python:
  - 2.7
env:
  - BUILD_TYPE="Release"
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  # Print NumPy version that is already installed by Travis CI:
  - python -c "import numpy; print numpy.__version__"
  - cd ..
before_script:
  # Print CPU info for debugging purposes:
  - cat /proc/cpuinfo
  - gfortran -v
  - /usr/bin/f95 -v
install:
  - pwd
  - git clone --branch=master --depth=100 git://github.com/clawpack/clawutil
  - git clone --branch=master --depth=100 git://github.com/clawpack/riemann
  - ls
  - export CLAW=./
  - cd classic
script:
  - cd tests/acoustics3d/
  - make .output
notifications:
  email: false
